import { readFileSync } from 'node:fs';
const H = readFileSync(new URL('./helpers.js', import.meta.url), 'utf8');
const s = (name, body, shot = false) => ({ name, shot, code: `(()=>{ const O=[6,1.5,-97]; const L=(x,y,z)=>T.V(x+O[0],y+O[1],z+O[2]); ${body} })()` });
export const steps = [
  { name: 'helpers', code: H },
  s('start', `const d=__director; d.startAt(1, true); d.ui.fade(0,0); T.step(1.0); return T.state();`, true),
  s('carry_a', `const a=T.lat('c_a').position(); T.walkTo(a.x, a.z+1.0, {tol:0.3}); T.lookAt(a.x,a.y,a.z); T.step(0.1); T.tap('use'); T.step(0.3); const w=L(0,0,-9.4); T.walkTo(w.x, w.z, {tol:0.25}); T.lookAt(w.x, w.y+0.2, w.z-1.35); T.step(0.4); T.tap('use'); T.step(1.0); return {a:T.lat('c_a').position().toArray().map(v=>+v.toFixed(2)), s:T.state()};`, true),
  s('take_bol1', `const b=T.lat('bol1').object.position; T.lookAt(b.x, b.y+0.3, b.z); T.step(0.2); T.tap('take'); T.step(0.8); return T.state();`),
  s('grab_b', `const c=T.lat('c_b').position(); T.walkTo(c.x+0.9, c.z+0.9, {tol:0.3}); T.lookAt(c.x,c.y,c.z); T.step(0.1); T.tap('use'); T.step(0.4); return T.state();`),
  s('mount_a', `const a=T.lat('c_a').position(); T.walkTo(a.x, a.z+1.2, {tol:0.25}); const r=T.runJump(a.x, a.z, 0.1, 0.4); T.step(0.3); return {r, s:T.state()};`, true),
  s('give_a1', `const a=T.lat('c_a').position(); T.lookAt(a.x, a.y, a.z); T.step(0.1); const t=__game.graft.target&&__game.graft.target.id; T.tap('give'); T.step(1.0); return {t, lvl:T.lat('c_a').level, s:T.state()};`, true),
  s('take_bol2', `const b=T.lat('bol2').object.position; T.lookAt(b.x, b.y+0.3, b.z); T.step(0.2); const t=__game.graft.target&&__game.graft.target.id; T.tap('take'); T.step(0.8); return {t, s:T.state()};`),
  s('give_a2', `const a=T.lat('c_a').position(); T.lookAt(a.x, a.y, a.z); T.step(0.1); const t=__game.graft.target&&__game.graft.target.id; T.tap('give'); T.step(1.2); return {t, lvl:T.lat('c_a').level, a:T.lat('c_a').position().toArray().map(v=>+v.toFixed(2)), s:T.state()};`, true),
  s('drop_b', `const a=T.lat('c_a').position(); T.lookAt(a.x, a.y+1.0, a.z-0.6); T.step(0.4); T.tap('use'); T.step(1.2); return {b:T.lat('c_b').position().toArray().map(v=>+v.toFixed(2)), s:T.state()};`, true),
  s('mount_b', `const b=T.lat('c_b').position(); const r=T.runJump(b.x, b.z, 0.0, 0.2); T.step(0.3); return {r, b:T.lat('c_b').position().toArray().map(v=>+v.toFixed(2)), s:T.state()};`),
  s('take_bol3', `const b=T.lat('bol3').object.position; T.lookAt(b.x, b.y+0.3, b.z); T.step(0.2); const t=__game.graft.target&&__game.graft.target.id; T.tap('take'); T.step(0.8); return {t, s:T.state()};`),
  s('give_b', `const b=T.lat('c_b').position(); T.lookAt(b.x, b.y, b.z); T.step(0.1); const t=__game.graft.target&&__game.graft.target.id; T.tap('give'); T.step(1.2); return {t, lvl:T.lat('c_b').level, s:T.state()};`, true),
  s('take_bol4', `const b=T.lat('bol4').object.position; T.lookAt(b.x, b.y+0.3, b.z); T.step(0.2); const t=__game.graft.target&&__game.graft.target.id; T.tap('take'); T.step(0.8); return {t, s:T.state()};`),
  s('jump_terrace', `const w=L(0,4.3,-14.5); const r=T.runJump(w.x, w.z, 0.15, 0.9); T.step(0.5); return {r, s:T.state()};`, true),
  s('look_back', `const w=L(0,0,4); T.lookAt(w.x, w.y, w.z); T.step(1.6); return T.state();`, true),
  s('garden_falls', `T.step(2.0); const g=__game.islands[1].chunks.get('garden'); return {fall: g.fall && +g.fall.t.toFixed(2), s:T.state()};`, true),
  s('garden_gone', `T.step(4.0); return T.state();`, true),
  s('carry_c', `const c=T.lat('c_c').position(); T.walkTo(c.x-0.9, c.z+0.6, {tol:0.3}); T.lookAt(c.x,c.y,c.z); T.step(0.1); const t=__game.graft.target&&__game.graft.target.id; T.tap('use'); T.step(0.4); return {t, s:T.state()};`),
  s('plate_c', `const p=L(-4,4.3,-15.4); T.walkTo(p.x+1.3, p.z+0.2, {tol:0.25}); T.lookAt(p.x, p.y+0.4, p.z); T.step(0.4); T.tap('use'); T.step(1.5); const gate=T.ent('gate'); return {c:T.lat('c_c').position().toArray().map(v=>+v.toFixed(2)), open:+gate.t.toFixed(2), s:T.state()};`, true),
  s('through_gate', `const a=L(0,4.3,-18.6); T.walkTo(a.x, a.z, {tol:0.3}); const b=L(0,4.3,-22.0); const r=T.walkTo(b.x, b.z, {tol:0.3}); return {r, s:T.state()};`, true),
  s('carry_d', `const c=T.lat('c_d').position(); T.walkTo(c.x+0.9, c.z+0.6, {tol:0.3}); T.lookAt(c.x,c.y,c.z); T.step(0.1); T.tap('use'); T.step(0.3); const w=L(3.5,4.3,-25.2); T.walkTo(w.x, w.z, {tol:0.25}); T.lookAt(w.x, w.y+0.5, w.z-1.4); T.step(0.4); T.tap('use'); T.step(1.0); return {d:T.lat('c_d').position().toArray().map(v=>+v.toFixed(2)), s:T.state()};`, true),
  s('mount_d', `const d=T.lat('c_d').position(); T.walkTo(d.x, d.z+0.75, {tol:0.15}); T.step(0.3); const r=T.runJump(d.x, d.z, 0.0, 0.2); T.step(0.3); return {r, s:T.state()};`),
  s('give_d1', `const d=T.lat('c_d').position(); T.lookAt(d.x, d.y, d.z); T.step(0.1); const t=__game.graft.target&&__game.graft.target.id; T.tap('give'); T.step(1.2); return {t, lvl:T.lat('c_d').level, s:T.state()};`, true),
  s('take_c', `const c=T.lat('c_c').position(); T.lookAt(c.x, c.y, c.z); T.step(0.2); const t=__game.graft.target&&__game.graft.target.id; T.tap('take'); T.step(2.5); const gate=T.ent('gate'); return {t, lvl:T.lat('c_c').level, gate:+gate.t.toFixed(2), s:T.state()};`, true),
  s('give_d2', `const d=T.lat('c_d').position(); T.lookAt(d.x, d.y, d.z); T.step(0.1); const t=__game.graft.target&&__game.graft.target.id; T.tap('give'); T.step(1.5); return {t, lvl:T.lat('c_d').level, d:T.lat('c_d').position().toArray().map(v=>+v.toFixed(2)), s:T.state()};`, true),
  s('jump_ledge', `const w=L(3.3,7.6,-28.6); const r=T.runJump(w.x, w.z, 0.1, 0.9); return {r, s:T.state()};`, true),
  s('to_bloom', `const b=L(0,7.9,-31); const r=T.walkTo(b.x, b.z, {tol:0.4}); T.step(1.0); return {r, s:T.state()};`, true),
  s('bloom_view', `const w=L(0,6,-60); T.lookAt(w.x, w.y, w.z); T.step(3.0); return T.state();`, true),
];
