import { readFileSync } from 'node:fs';
const H = readFileSync(new URL('./helpers.js', import.meta.url), 'utf8');
const s = (name, body, shot = false) => ({ name, shot, code: `(()=>{ const O=[14,8.0,-173.2]; const L=(x,y,z)=>T.V(x+O[0],y+O[1],z+O[2]); const P=()=>{const p=__game.player; return [+(p.pos.x-O[0]).toFixed(2), +(p.feet.y-O[1]).toFixed(2), +(p.pos.z-O[2]).toFixed(2)];}; ${body} })()` });
const look = (x, y, z) => `{const w=L(${x},${y},${z}); T.lookAt(w.x,w.y,w.z); T.step(0.15);}`;
const tgt = `(__game.graft.target&&__game.graft.target.id)`;
export const steps = [
  { name: 'helpers', code: H },
  s('start', `const d=__director; d.startAt(d.plan.findIndex(p=>p.key==='c_viaduct'), true); d.ui.fade(0,0); T.step(1.0); return {p:P(), s:T.state()};`, true),
  s('to_lookout', `const a=L(-3.8,0,9.5); T.walkTo(a.x,a.z,{tol:0.3}); const b=L(-11.4,0,9.5); const r=T.walkTo(b.x,b.z,{tol:0.4}); return {r, p:P()};`, true),
  s('seed', `const b=L(-11.6,0,9.5); T.walkTo(b.x,b.z,{tol:0.3}); T.tap('use'); T.step(0.5); return {p:P(), seeds:__director.save.seeds};`),
  s('back', `const a=L(-3.2,0,9.5); const r=T.walkTo(a.x,a.z,{tol:0.3}); return {r, p:P()};`),
  s('take_look', `${look(-6.5,-0.2,9.5)} const t=${tgt}; T.tap('take'); T.step(1.2); return {t, s:T.state()};`, true),
  s('give_a', `const a=L(0,0,5.6); T.walkTo(a.x,a.z,{tol:0.3}); ${look(0,-0.15,3.7)} const t=${tgt}; T.tap('give'); T.step(2.2); return {t, s:T.state()};`, true),
  s('cross_a', `const a=L(0,0,-4.6); const r=T.walkTo(a.x,a.z,{tol:0.3}); return {r, p:P()};`),
  s('take_a', `${look(0,-0.2,0.5)} const t=${tgt}; T.tap('take'); T.step(2.0); return {t, s:T.state()};`, true),
  s('abutment_falls', `T.step(2.5); return {p:P()};`, true),
  s('give_p1', `const a=L(0,0,-8.6); T.walkTo(a.x,a.z,{tol:0.25}); ${look(0,0,-9.4)} const t=${tgt}; T.tap('give'); T.step(1.4); return {t, p:P(), s:T.state()};`, true),
  s('jump_upper', `const w=L(0,2.8,-11.6); const r=T.runJump(w.x,w.z,0.05,0.8); return {r:P()};`),
  s('take_p1', `const a=L(0,2.8,-10.45); T.walkTo(a.x,a.z,{tol:0.2}); ${look(0,1.5,-8.9)} const t=${tgt}; T.tap('take'); T.step(1.2); return {t, s:T.state()};`, true),
  s('give_b', `const a=L(0,2.8,-18.9); T.walkTo(a.x,a.z,{tol:0.3}); ${look(0,2.65,-20.3)} const t=${tgt}; T.tap('give'); T.step(2.0); return {t, s:T.state()};`, true),
  s('cross_b', `const a=L(0,2.8,-27.2); const r=T.walkTo(a.x,a.z,{tol:0.3}); ${look(0,2.6,-23.0)} const t=${tgt}; T.tap('take'); T.step(1.6); return {r, t, p:P(), s:T.state()};`, true),
  s('grab_crate', `const c=T.lat('c_m').position(); T.walkTo(c.x-0.2, c.z+1.1,{tol:0.3}); T.lookAt(c.x,c.y,c.z); T.step(0.1); T.tap('use'); T.step(0.4); return {s:T.state()};`),
  s('give_c', `const a=L(0,2.8,-29.9); T.walkTo(a.x,a.z,{tol:0.3}); ${look(0,2.65,-31.3)} const t=${tgt}; T.tap('give'); T.step(2.0); return {t, s:T.state()};`, true),
  s('take_crate_cell', `${look(1.4,2.8,-29.6)} T.step(0.3); T.tap('use'); T.step(0.8); const c=T.lat('c_m').position(); T.lookAt(c.x,c.y,c.z); T.step(0.2); const t=${tgt}; T.tap('take'); T.step(1.0); const c2=T.lat('c_m').position(); T.lookAt(c2.x,c2.y,c2.z); T.step(0.1); T.tap('use'); T.step(0.4); return {t, lvl:T.lat('c_m').level, s:T.state()};`, true),
  s('drop_onto_pillar', `const a=L(0,2.8,-34.6); T.walkTo(a.x,a.z,{tol:0.3}); const b=L(0,0,-36.3); T.walkTo(b.x,b.z,{tol:0.3, max:6}); T.step(1.0); return {p:P(), s:T.state()};`, true),
  s('give_pmid', `${look(0,-0.3,-36.3)} const t=${tgt}; T.tap('give'); T.step(3.2); return {t, p:P(), s:T.state()};`, true),
  s('onto_deck', `const a=L(0,4.8,-39.4); const r=T.walkTo(a.x,a.z,{tol:0.3}); return {r, p:P(), s:T.state()};`, true),
  s('take_behind', `${look(0,2.6,-33.0)} const t=${tgt}; T.tap('take'); T.step(1.6); return {t, s:T.state()};`, true),
  s('place_crate', `const a=L(4.9,4.8,-42.4); T.walkTo(a.x,a.z,{tol:0.25}); ${look(3.4,5.2,-42.5)} T.step(0.4); T.tap('use'); T.step(1.2); const c=T.lat('c_m').position(); return {c:[+(c.x-O[0]).toFixed(2), +(c.y-O[1]).toFixed(2), +(c.z-O[2]).toFixed(2)], s:T.state()};`, true),
  s('give_ram', `${look(3.4,5.36,-40.2)} const t=${tgt}; T.tap('give'); T.step(3.2); const c=T.lat('c_m').position(); const pl=T.ent('plate_h'); return {t, c:[+(c.x-O[0]).toFixed(2), +(c.y-O[1]).toFixed(2), +(c.z-O[2]).toFixed(2)], w:pl&&pl.weight, s:T.state()};`, true),
  s('take_ram', `${look(3.4,5.36,-42.5)} const t=${tgt}; T.tap('take'); T.step(2.6); return {t, s:T.state()};`),
  s('grow_crate1', `const a=L(3.4,4.8,-43.0); T.walkTo(a.x,a.z,{tol:0.25}); const c=T.lat('c_m').position(); T.lookAt(c.x,c.y+0.2,c.z); T.step(0.15); const t=${tgt}; T.tap('give'); T.step(2.0); return {t, lvl:T.lat('c_m').level, s:T.state()};`, true),
  s('take_s_c', `const a=L(0,4.8,-38.2); T.walkTo(a.x,a.z,{tol:0.25}); ${look(0,2.6,-33.0)} const t=${tgt}; T.tap('take'); T.step(2.0); return {t, s:T.state()};`, true),
  s('grow_crate2', `const a=L(3.4,4.8,-43.0); T.walkTo(a.x,a.z,{tol:0.25}); const c=T.lat('c_m').position(); T.lookAt(c.x,c.y+0.45,c.z); T.step(0.15); const t=${tgt}; T.tap('give'); T.step(2.0); const pl=T.ent('plate_h'); const g=[...__game.entities.values()].find(e=>e.id==='c_viaduct.gate'); return {t, lvl:T.lat('c_m').level, w:pl&&pl.weight, gate:g&&+g.t.toFixed(2), s:T.state()};`, true),
  s('enter', `const a=L(0,4.8,-42.0); T.walkTo(a.x,a.z,{tol:0.3}); const b=L(-0.6,4.8,-47.2); const r=T.walkTo(b.x,b.z,{tol:0.3}); return {r, p:P()};`, true),
  s('upgrade', `const b=L(-1.2,4.8,-47.4); T.walkTo(b.x,b.z,{tol:0.3}); T.tap('use'); T.step(1.0); return {cap:__game.graft.capacity, s:T.state()};`, true),
  s('take_crate2', `const a=L(0.9,4.8,-46.0); T.walkTo(a.x,a.z,{tol:0.3}); const c=T.lat('c_m').position(); T.lookAt(c.x,c.y,c.z); T.step(0.15); const t=${tgt}; T.tap('take'); T.step(1.0); T.lookAt(c.x,c.y-0.5,c.z); T.step(0.2); T.tap('take'); T.step(1.0); return {t, lvl:T.lat('c_m').level, s:T.state()};`, true),
  s('give_p2', `const a=L(-2.5,4.8,-50.6); T.walkTo(a.x,a.z,{tol:0.25}); ${look(-2.5,4.8,-51.3)} const t=${tgt}; T.tap('give'); T.step(1.2); ${look(-2.5,6.3,-51.3)} T.tap('give'); T.step(1.6); return {t, p:P(), s:T.state()};`, true),
  s('jump_mezz', `const w=L(-2.3,9.1,-53.4); const r=T.runJump(w.x,w.z,0.05,0.9); return {r:P()};`, true),
  s('to_bloom', `const b=L(0,9.4,-54); const r=T.walkTo(b.x,b.z,{tol:0.4}); T.step(1.5); return {r, p:P()};`, true),
  s('bloom_view', `${look(0,9,-80)} T.step(2.0); return {p:P()};`, true),
];
